# Generated by Django 3.2.3 on 2021-05-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
