# Generated by Django 3.2.3 on 2021-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('exp_salary', models.IntegerField()),
                ('relocate', models.NullBooleanField(default=False)),
            ],
        ),
    ]
