# Generated by Django 3.2.3 on 2021-06-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_c_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='c_username',
        ),
    ]
