# Generated by Django 3.2.3 on 2021-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_c_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='iscandidate',
            field=models.BooleanField(default=False),
        ),
    ]
