# Generated by Django 3.2.4 on 2021-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_remove_candidate_iscandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default=None, upload_to=None),
        ),
    ]
