# Generated by Django 3.2.3 on 2021-06-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0003_candidatejobmatch'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_desc',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=100, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_age',
            field=models.IntegerField(verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_age',
            field=models.IntegerField(verbose_name='Minimum Age'),
        ),
        migrations.AlterField(
            model_name='job',
            name='n_openings',
            field=models.IntegerField(verbose_name='Number of Openings'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(verbose_name='Salary'),
        ),
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Candidate')),
                ('job_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate', verbose_name='Job Applied For')),
            ],
        ),
    ]
