# Generated by Django 3.2.3 on 2021-06-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidatejobmatch'),
        ('job', '0002_auto_20210603_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplied',
            name='job_applied',
        ),
        migrations.AlterField(
            model_name='jobapplied',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate', verbose_name='Candidate'),
        ),
    ]
