# Generated by Django 3.2.3 on 2021-06-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210603_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplied',
        ),
    ]
