# Generated by Django 3.2.3 on 2021-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_delete_jobapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newname', models.CharField(max_length=10)),
            ],
        ),
    ]
