# Generated by Django 3.2.3 on 2021-06-03 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidatejobmatch'),
        ('job', '0005_jobapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate', verbose_name='Candidate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplied',
            name='newname',
            field=models.CharField(max_length=100),
        ),
    ]
