# Generated by Django 3.2.3 on 2021-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobapplied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplied',
        ),
    ]
