# Generated by Django 3.2.3 on 2021-06-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobapplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplied',
            old_name='usernmae',
            new_name='username',
        ),
    ]
