# Generated by Django 3.2.3 on 2021-06-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_usernmae_jobapplied_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=50),
        ),
    ]
