# Generated by Django 3.2.4 on 2021-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20210609_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='files',
            field=models.FileField(default=None, upload_to=None),
        ),
    ]
