# Generated by Django 3.2.4 on 2021-06-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='files',
            field=models.FileField(default=None, upload_to='files'),
        ),
    ]
